#!/usr/bin/env python3
"""List every incident bundle's replay review status.

Scans ``incidents/`` and reports per-incident:

* incident_id, run_id, scenario_id (from incident-report.json)
* replay-review manifest presence
* bag_status, replay_execution_status, evidence_origin
* missing topic count, marker count

Usage:
    rover_ws/tools/list_replay_reviews.py
        [--incidents-root incidents]
        [--json]
        [--md-out docs/REPLAY_REVIEW_INDEX.md]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from _probe_common import ensure_app_on_path  # noqa: E402

ensure_app_on_path()


def _scan_incident_dir(path: Path) -> dict:
    incident_path = path / "incident-report.json"
    manifest_path = path / "replay-review-manifest.json"
    report_path = path / "replay-review-report.json"
    out: dict = {
        "incident_id": path.name,
        "manifest_present": manifest_path.exists(),
        "report_present": report_path.exists(),
        "bag_status": "missing",
        "replay_execution_status": "missing",
        "evidence_origin": "unknown",
        "marker_count": 0,
        "missing_topics_count": 0,
        "incident_present": incident_path.exists(),
    }
    if incident_path.exists():
        try:
            payload = json.loads(incident_path.read_text(encoding="utf-8"))
            out["incident_id"] = payload.get("incident_id", path.name)
            out["run_id"] = payload.get("run_id")
            out["scenario_id"] = payload.get("scenario_id")
            out["evidence_status"] = payload.get("evidence_status", "")
        except json.JSONDecodeError:
            pass
    if manifest_path.exists():
        try:
            payload = json.loads(manifest_path.read_text(encoding="utf-8"))
            out["bag_status"] = payload.get("bag_status", "missing")
            out["marker_count"] = int(payload.get("timeline_marker_count", 0))
            out["missing_topics_count"] = len(payload.get("missing_topics", []))
        except json.JSONDecodeError:
            pass
    if report_path.exists():
        try:
            payload = json.loads(report_path.read_text(encoding="utf-8"))
            out["replay_execution_status"] = payload.get(
                "replay_execution_status", out["bag_status"]
            )
            out["evidence_origin"] = payload.get("evidence_origin", "unknown")
        except json.JSONDecodeError:
            pass
    return out


def _render_md(rows: list[dict], *, root: Path) -> str:
    lines: list[str] = []
    lines.append("# Replay Review Index")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/list_replay_reviews.py`. The "
        "platform is **not safety-certified**; this index is "
        "engineering analysis material._"
    )
    lines.append("")
    lines.append(f"- **Incidents root:** `{root}`")
    lines.append(f"- **Bundles inspected:** {len(rows)}")
    lines.append("")
    if not rows:
        lines.append("_No incident bundles found._")
        return "\n".join(lines) + "\n"
    lines.append(
        "| Incident | Scenario | Evidence | Bag | Replay | Origin | Markers | Missing topics |"
    )
    lines.append("|---|---|---|---|---|---|---|---|")
    for r in rows:
        lines.append(
            f"| `{r['incident_id']}` | `{r.get('scenario_id') or '-'}` | "
            f"`{r.get('evidence_status', '-')}` | `{r['bag_status']}` | "
            f"`{r['replay_execution_status']}` | `{r['evidence_origin']}` | "
            f"{r['marker_count']} | {r['missing_topics_count']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--incidents-root", type=Path, default=Path("incidents"))
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--md-out", type=Path, default=None)
    args = parser.parse_args(argv)

    if not args.incidents_root.exists():
        print("no incidents dir", file=sys.stderr)
        return 0

    rows: list[dict] = []
    for path in sorted(args.incidents_root.iterdir()):
        if not path.is_dir() or path.name == "comparisons":
            continue
        rows.append(_scan_incident_dir(path))

    if args.json:
        json.dump({"rows": rows}, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
    else:
        print(f"replay-review-index: rows={len(rows)}")
        for r in rows:
            print(
                f"  {r['incident_id']:<40s} bag={r['bag_status']:<14s} "
                f"replay={r['replay_execution_status']:<14s} "
                f"origin={r['evidence_origin']:<18s} markers={r['marker_count']}"
            )

    if args.md_out is not None:
        args.md_out.parent.mkdir(parents=True, exist_ok=True)
        args.md_out.write_text(_render_md(rows, root=args.incidents_root), encoding="utf-8")

    return 0


if __name__ == "__main__":
    sys.exit(main())
