"""Phase 13 live-runtime package.

The platform is **not safety-certified**. The live-runtime layer is
read-only with respect to runtime state: it builds, validates,
classifies, and reports on live-run evidence. It never fabricates
bags, never marks static evidence as bag-backed, and never claims
live execution unless a real run produced real artefacts.
"""

from __future__ import annotations

from .bag_manifest import (
    REQUIRED_FIELDS as BAG_MANIFEST_REQUIRED_FIELDS,
    bag_manifest_from_dict,
    bag_manifest_is_bag_backed,
    bag_manifest_to_dict,
    build_not_executed_manifest,
    degrade_to_partial_if_missing,
    load_bag_manifest,
    validate_bag_manifest,
    write_bag_manifest,
)
from .evidence_capture import (
    build_not_executed_bundle,
    detect_environment_block_reason,
    evidence_bundle_missing_files,
    evidence_bundle_required_files,
    init_run_directory,
    write_evidence_bundle,
    write_known_limitations_md,
    write_live_run_summary,
    write_metadata,
    write_qualification_summary_md,
)
from .maturity import aggregate_maturity
from .models import (
    BAG_STATUS_BAG_BACKED,
    BAG_STATUS_INVALID,
    BAG_STATUS_MISSING_BAG,
    BAG_STATUS_NOT_EXECUTED,
    BAG_STATUS_PARTIAL,
    BAG_STATUSES,
    LIVE_RUN_STATUS_FAILED,
    LIVE_RUN_STATUS_NOT_EXECUTED,
    LIVE_RUN_STATUS_PARTIAL,
    LIVE_RUN_STATUS_PASSED,
    LIVE_RUN_STATUS_SKIPPED,
    LIVE_RUN_STATUSES,
    LIVE_RUNTIME_DISCLAIMER,
    QUALIFICATION_STATUS_NOT_QUALIFIED,
    QUALIFICATION_STATUS_PARTIAL,
    QUALIFICATION_STATUS_QUALIFIED,
    QUALIFICATION_STATUS_UNKNOWN,
    REQUIRED_EVIDENCE_FILES,
    BagManifest,
    LiveRunSummary,
    LiveRuntimeMaturityCounters,
    LiveRuntimeMaturityReport,
    RunnerProfile,
    ScenarioPlan,
    ScenarioPlanEntry,
)
from .report import (
    maturity_report_to_dict,
    render_maturity_markdown,
    write_maturity_json,
    write_maturity_markdown,
)
from .runner_profile import (
    labels_match,
    load_runner_profile,
    runner_profile_from_dict,
    runner_profile_schema,
    runner_profile_to_dict,
    runner_supports_live_execution,
    update_qualification_status,
    validate_runner_profile,
    write_runner_profile,
    write_runner_profile_schema,
)
from .scenario_plan import (
    load_scenario_plan,
    scenario_plan_from_dict,
    scenario_plan_to_dict,
    validate_scenario_plan,
)


__all__ = [
    "LIVE_RUNTIME_DISCLAIMER",
    "REQUIRED_EVIDENCE_FILES",
    "LIVE_RUN_STATUSES",
    "BAG_STATUSES",
    "LIVE_RUN_STATUS_PASSED",
    "LIVE_RUN_STATUS_FAILED",
    "LIVE_RUN_STATUS_PARTIAL",
    "LIVE_RUN_STATUS_SKIPPED",
    "LIVE_RUN_STATUS_NOT_EXECUTED",
    "BAG_STATUS_BAG_BACKED",
    "BAG_STATUS_MISSING_BAG",
    "BAG_STATUS_PARTIAL",
    "BAG_STATUS_NOT_EXECUTED",
    "BAG_STATUS_INVALID",
    "QUALIFICATION_STATUS_QUALIFIED",
    "QUALIFICATION_STATUS_PARTIAL",
    "QUALIFICATION_STATUS_NOT_QUALIFIED",
    "QUALIFICATION_STATUS_UNKNOWN",
    "RunnerProfile",
    "ScenarioPlan",
    "ScenarioPlanEntry",
    "BagManifest",
    "LiveRunSummary",
    "LiveRuntimeMaturityCounters",
    "LiveRuntimeMaturityReport",
    "BAG_MANIFEST_REQUIRED_FIELDS",
    "bag_manifest_from_dict",
    "bag_manifest_to_dict",
    "build_not_executed_manifest",
    "degrade_to_partial_if_missing",
    "load_bag_manifest",
    "validate_bag_manifest",
    "write_bag_manifest",
    "bag_manifest_is_bag_backed",
    "build_not_executed_bundle",
    "detect_environment_block_reason",
    "evidence_bundle_missing_files",
    "evidence_bundle_required_files",
    "init_run_directory",
    "write_evidence_bundle",
    "write_known_limitations_md",
    "write_live_run_summary",
    "write_metadata",
    "write_qualification_summary_md",
    "aggregate_maturity",
    "maturity_report_to_dict",
    "render_maturity_markdown",
    "write_maturity_json",
    "write_maturity_markdown",
    "labels_match",
    "load_runner_profile",
    "runner_profile_from_dict",
    "runner_profile_schema",
    "runner_profile_to_dict",
    "runner_supports_live_execution",
    "update_qualification_status",
    "validate_runner_profile",
    "write_runner_profile",
    "write_runner_profile_schema",
    "load_scenario_plan",
    "scenario_plan_from_dict",
    "scenario_plan_to_dict",
    "validate_scenario_plan",
]
