"""Render incident reports and bundles.

The reporter consumes a fully-populated :class:`Incident` and produces:

* ``incident-report.md`` (operator-readable),
* ``incident-report.json`` (machine-readable),
* ``timeline.md``, ``timeline.json``, ``timeline-sequence.mmd``,
  ``timeline-state.mmd``,
* ``causality.md``,
* ``recommendations.md``,
* ``evidence-manifest.json``,
* ``foxglove-replay-hints.json``.

Every report carries the certification disclaimer verbatim. Missing
and contradictory evidence are surfaced in dedicated sections. The
reporter never invents data; it only renders what the classifier and
causality engine produced.
"""

from __future__ import annotations

import json
from pathlib import Path

from app.incident_analysis.models import (
    CERTIFICATION_DISCLAIMER,
    CausalityChain,
    CausalityConfidence,
    Incident,
    IncidentBundle,
)
from app.incident_analysis.timeline import (
    render_sequence_mmd,
    render_state_mmd,
    render_timeline_md,
)


def write_incident_bundle(
    incident: Incident,
    *,
    bundle_dir: Path,
) -> IncidentBundle:
    """Materialise every report file under ``bundle_dir``.

    The function only writes; it does not mutate ``incident``.
    """

    bundle_dir.mkdir(parents=True, exist_ok=True)
    _write_json(bundle_dir / "incident-report.json", incident.as_dict())
    (bundle_dir / "incident-report.md").write_text(
        render_incident_report_md(incident), encoding="utf-8"
    )
    if incident.timeline is not None:
        _write_json(bundle_dir / "timeline.json", incident.timeline.as_dict())
        (bundle_dir / "timeline.md").write_text(
            render_timeline_md(incident.timeline), encoding="utf-8"
        )
        (bundle_dir / "timeline-sequence.mmd").write_text(
            render_sequence_mmd(incident.timeline), encoding="utf-8"
        )
        (bundle_dir / "timeline-state.mmd").write_text(
            render_state_mmd(incident.timeline), encoding="utf-8"
        )
    (bundle_dir / "causality.md").write_text(
        render_causality_md(incident), encoding="utf-8"
    )
    (bundle_dir / "recommendations.md").write_text(
        render_recommendations_md(incident), encoding="utf-8"
    )
    _write_json(
        bundle_dir / "evidence-manifest.json", incident.evidence_manifest.as_dict()
    )
    if incident.foxglove_hint is not None:
        _write_json(
            bundle_dir / "foxglove-replay-hints.json",
            incident.foxglove_hint.as_dict(),
        )
    return IncidentBundle(incident=incident, bundle_dir=bundle_dir)


def render_incident_report_md(incident: Incident) -> str:
    lines: list[str] = []
    lines.append(f"# Incident Report — `{incident.incident_id}`")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/reconstruct_incident.py`. "
        "The platform is **not safety-certified**; this report is an "
        "engineering analysis artefact._"
    )
    lines.append("")
    lines.append(f"- **Run id:** `{incident.run_id or '-'}`")
    lines.append(f"- **Scenario id:** `{incident.scenario_id or '-'}`")
    lines.append(f"- **Severity:** `{incident.severity.value}`")
    lines.append(f"- **Outcome:** `{incident.outcome.value}`")
    lines.append(f"- **Evidence status:** `{incident.evidence_status.value}`")
    if incident.cause is not None:
        lines.append(
            f"- **Best-evidence cause:** `{incident.cause.label}` "
            f"(`{incident.cause.confidence.value}`)"
        )
    lines.append(f"- **Generated:** {incident.generated_at_utc}")
    lines.append("")

    lines.append("## Safety state sequence")
    lines.append("")
    if incident.safety_states:
        lines.append(" -> ".join(f"`{s}`" for s in incident.safety_states))
    else:
        lines.append("_No safety transitions in available evidence._")
    lines.append("")

    if incident.mission_states:
        lines.append("## Mission state sequence")
        lines.append("")
        lines.append(" -> ".join(f"`{s}`" for s in incident.mission_states))
        lines.append("")

    if incident.fault_ids:
        lines.append("## Faults observed")
        lines.append("")
        for fid in incident.fault_ids:
            lines.append(f"- `{fid}`")
        lines.append("")

    lines.append("## Command authorisation summary")
    lines.append("")
    summary_entry = _command_audit_entry(incident)
    if summary_entry is None:
        lines.append("_No command-audit summary in available evidence._")
    else:
        attrs = summary_entry.attributes
        lines.append(
            f"- Requests: {attrs.get('request_count', '?')}\n"
            f"- Authorised commands: {attrs.get('command_count', '?')}\n"
            f"- Clamped: {attrs.get('clamped_count', '?')}\n"
            f"- Zeroed: {attrs.get('zeroed_count', '?')}\n"
            f"- Rejected: {attrs.get('rejected_count', '?')}\n"
            f"- Audit ok: {attrs.get('ok', '?')}"
        )
    lines.append("")

    lines.append("## Replay integrity summary")
    lines.append("")
    replay_entry = _replay_integrity_entry(incident)
    if replay_entry is None:
        lines.append("_No replay-integrity summary in available evidence._")
    else:
        attrs = replay_entry.attributes
        lines.append(
            f"- Status: `{attrs.get('status', '?')}`\n"
            f"- Events: {attrs.get('event_count', '?')}\n"
            f"- Transitions: {attrs.get('transition_count', '?')}"
        )
    lines.append("")

    lines.append("## Causality chain")
    lines.append("")
    if not incident.causality_chains:
        lines.append("_No causality chain matched the available evidence._")
    else:
        for chain in incident.causality_chains:
            lines.append(
                f"### `{chain.chain_id}` ({chain.overall_confidence.value})"
            )
            lines.append("")
            lines.append(f"_{chain.description}_")
            lines.append("")
            if chain.links:
                lines.append("| From | To | Relation | Confidence | Inferred | Rationale |")
                lines.append("|---|---|---|---|---|---|")
                for link in chain.links:
                    lines.append(
                        f"| #{link.from_entry_index} | #{link.to_entry_index} | "
                        f"`{link.relation}` | `{link.confidence.value}` | "
                        f"{'yes' if link.inferred else 'no'} | {link.rationale} |"
                    )
            if chain.missing_links:
                lines.append("")
                lines.append("**Missing links:**")
                for missing in chain.missing_links:
                    lines.append(f"- {missing}")
            if chain.contradictions:
                lines.append("")
                lines.append("**Contradictions:**")
                for c in chain.contradictions:
                    lines.append(f"- {c}")
            lines.append("")

    lines.append("## Missing evidence")
    lines.append("")
    if incident.missing_evidence:
        for line in incident.missing_evidence:
            lines.append(f"- {line}")
    else:
        lines.append("_None recorded._")
    lines.append("")

    lines.append("## Contradictory evidence")
    lines.append("")
    if incident.contradictions:
        for line in incident.contradictions:
            lines.append(f"- {line}")
    else:
        lines.append("_None recorded._")
    lines.append("")

    if incident.operational_interpretation:
        lines.append("## Operational interpretation")
        lines.append("")
        lines.append(incident.operational_interpretation)
        lines.append("")

    lines.append("## Recommended follow-up")
    lines.append("")
    if incident.recommended_follow_up:
        for line in incident.recommended_follow_up:
            lines.append(f"- {line}")
    else:
        lines.append("_None recorded._")
    lines.append("")

    lines.append("## Certification disclaimer")
    lines.append("")
    lines.append(CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_causality_md(incident: Incident) -> str:
    lines: list[str] = []
    lines.append(f"# Causality — `{incident.incident_id}`")
    lines.append("")
    if not incident.causality_chains:
        lines.append("_No causality chain matched the available evidence._")
        lines.append("")
        lines.append(CERTIFICATION_DISCLAIMER)
        lines.append("")
        return "\n".join(lines)
    for chain in incident.causality_chains:
        lines.append(f"## `{chain.chain_id}` — `{chain.overall_confidence.value}`")
        lines.append("")
        lines.append(chain.description)
        lines.append("")
        if chain.links:
            lines.append("```mermaid")
            lines.append("flowchart LR")
            for link in chain.links:
                tag = (
                    f"{link.relation} ({link.confidence.value}"
                    + (", inferred" if link.inferred else "")
                    + ")"
                )
                lines.append(
                    f"    E{link.from_entry_index} -- \"{tag}\" --> "
                    f"E{link.to_entry_index}"
                )
            lines.append("```")
            lines.append("")
        if chain.missing_links:
            lines.append("**Missing links:**")
            for m in chain.missing_links:
                lines.append(f"- {m}")
            lines.append("")
        if chain.contradictions:
            lines.append("**Contradictions:**")
            for c in chain.contradictions:
                lines.append(f"- {c}")
            lines.append("")
    lines.append(CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_recommendations_md(incident: Incident) -> str:
    lines: list[str] = []
    lines.append(f"# Recommendations — `{incident.incident_id}`")
    lines.append("")
    if incident.recommended_follow_up:
        for r in incident.recommended_follow_up:
            lines.append(f"- {r}")
    else:
        lines.append("_No automated recommendations were emitted._")
    lines.append("")
    if incident.missing_evidence:
        lines.append("## Evidence gaps")
        lines.append("")
        for line in incident.missing_evidence:
            lines.append(f"- {line}")
        lines.append("")
    if incident.contradictions:
        lines.append("## Contradictions")
        lines.append("")
        for line in incident.contradictions:
            lines.append(f"- {line}")
        lines.append("")
    lines.append(CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def derive_recommendations(incident: Incident) -> tuple[str, ...]:
    """Deterministic, evidence-driven recommendation strings."""

    out: list[str] = []
    if incident.evidence_status.value == "static_only":
        out.append(
            "Re-run on a Jazzy host to capture live runtime evidence; "
            "the current bundle is static-only."
        )
    if incident.evidence_status.value == "missing":
        out.append(
            "Re-run the underlying scenario / qualification flow; the "
            "bundle is missing the canonical evidence files."
        )
    if incident.contradictions:
        out.append(
            "Investigate the contradictions surfaced in this report; do "
            "not accept the outcome until they are resolved."
        )
    if any(c.missing_links for c in incident.causality_chains):
        out.append(
            "Causality chains contain inferred links; if a stronger "
            "claim is needed, capture the missing links by extending "
            "the recorder coverage."
        )
    if incident.outcome.value == "estop_latched":
        out.append(
            "E_STOP_LATCHED is terminal; verify operator-driven recovery "
            "is the only re-arming path before resuming the run."
        )
    if incident.outcome.value == "mission_aborted":
        out.append(
            "Mission abort: review world model events and recovery "
            "engagement counts to confirm the abort policy held."
        )
    if not out:
        out.append(
            "No automated recommendations; review the timeline and "
            "causality chains for further investigation."
        )
    return tuple(out)


def derive_operational_interpretation(incident: Incident) -> str:
    """One-paragraph human-readable summary."""

    pieces: list[str] = []
    if incident.scenario_id:
        pieces.append(
            f"The scenario `{incident.scenario_id}` produced an "
            f"`{incident.outcome.value}` outcome at severity "
            f"`{incident.severity.value}`."
        )
    if incident.cause is not None:
        pieces.append(
            f"Best-evidence cause: `{incident.cause.label}` "
            f"(confidence `{incident.cause.confidence.value}`)."
        )
    pieces.append(
        f"Evidence status is `{incident.evidence_status.value}`; "
        f"reviewers should weight the conclusions accordingly."
    )
    if incident.contradictions:
        pieces.append(
            "Contradictions were observed; the report does **not** treat "
            "this run as a clean pass."
        )
    return " ".join(pieces)


def _write_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def _command_audit_entry(incident: Incident):
    if incident.timeline is None:
        return None
    for entry in incident.timeline.entries:
        if (
            entry.category == "motion_arbitration"
            and entry.event_type == "motion_arbitration.summary"
        ):
            return entry
    return None


def _replay_integrity_entry(incident: Incident):
    if incident.timeline is None:
        return None
    for entry in incident.timeline.entries:
        if (
            entry.category == "replay"
            and entry.event_type == "replay.integrity_summary"
        ):
            return entry
    return None
