"""Filterable analytics index across incidents.

Builds a :class:`ReplayAnalyticsIndex` from the per-incident
analytics outputs. The index is a deterministic, filterable
manifest used by the CLI / docs to surface incidents at a glance.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

from app.replay_analytics.coverage import ReplayCoverageReport
from app.replay_analytics.loader import LoadedReplayBundle
from app.replay_analytics.models import (
    ReplayAnalyticsIndex,
    ReplayAnalyticsIndexRow,
    ReplayQualityScore,
    ReviewAudit,
)


def build_index(
    *,
    bundles: Iterable[LoadedReplayBundle],
    coverages: dict[str, ReplayCoverageReport],
    scores: dict[str, ReplayQualityScore],
    audits: dict[str, ReviewAudit],
) -> ReplayAnalyticsIndex:
    rows: list[ReplayAnalyticsIndexRow] = []
    for bundle in bundles:
        cov = coverages.get(bundle.incident_id)
        score = scores.get(bundle.incident_id)
        audit = audits.get(bundle.incident_id)
        marker_metric = cov.metric("marker_alignment_pct") if cov else None
        evidence_metric = (
            cov.metric("evidence_completeness_pct") if cov else None
        )
        contradictions = (
            len((bundle.incident_report or {}).get("contradictions") or [])
        )
        replay_validation = "missing"
        if bundle.replay_report is not None:
            replay_validation = bundle.replay_report.get(
                "replay_execution_status", "missing"
            )
        rows.append(
            ReplayAnalyticsIndexRow(
                incident_id=bundle.incident_id,
                scenario_id=(
                    bundle.incident_report.get("scenario_id")
                    if bundle.incident_report
                    else None
                ),
                quality_score=score.score if score else 0,
                coverage_status=(
                    score.coverage_status.value if score else "missing"
                ),
                review_completion_status=(
                    audit.status.value if audit else "not_started"
                ),
                bag_status=bundle.bag_status,
                evidence_origin=bundle.evidence_origin,
                marker_alignment_pct=(
                    marker_metric.value if marker_metric else None
                ),
                evidence_completeness_pct=(
                    evidence_metric.value if evidence_metric else None
                ),
                contradiction_count=contradictions,
                replay_validation_status=replay_validation,
            )
        )
    rows.sort(
        key=lambda r: (-int(r.quality_score), r.incident_id)
    )
    return ReplayAnalyticsIndex(rows=rows)


def write_index(
    index: ReplayAnalyticsIndex,
    *,
    json_path: Path,
    md_path: Path,
) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps(index.as_dict(), indent=2, sort_keys=True), encoding="utf-8"
    )
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(render_index_md(index), encoding="utf-8")


def render_index_md(index: ReplayAnalyticsIndex) -> str:
    lines: list[str] = []
    lines.append("# Replay Analytics Index")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/generate_replay_analytics.py`. "
        "Each row aggregates the Phase-6 incident bundle, the Phase-7 "
        "replay-review bundle, and the Phase-8 analytics output for a "
        "single incident. The platform is **not safety-certified**; "
        "this index is engineering analytics material._"
    )
    lines.append("")
    lines.append(f"- **Incidents indexed:** {len(index.rows)}")
    lines.append("")
    if not index.rows:
        lines.append("_No replay-review bundles inspected._")
        return "\n".join(lines) + "\n"
    lines.append(
        "| Incident | Scenario | Score | Coverage | Bag | Origin | "
        "Review | Marker% | Evidence% | Contradictions | Replay |"
    )
    lines.append(
        "|---|---|---|---|---|---|---|---|---|---|---|"
    )
    for r in index.rows:
        lines.append(
            "| `{incident}` | `{scenario}` | {score} | `{coverage}` | "
            "`{bag}` | `{origin}` | `{review}` | {marker} | "
            "{evidence} | {contradictions} | `{replay}` |".format(
                incident=r.incident_id,
                scenario=r.scenario_id or "-",
                score=r.quality_score,
                coverage=r.coverage_status,
                bag=r.bag_status,
                origin=r.evidence_origin,
                review=r.review_completion_status,
                marker=_fmt(r.marker_alignment_pct),
                evidence=_fmt(r.evidence_completeness_pct),
                contradictions=r.contradiction_count,
                replay=r.replay_validation_status,
            )
        )
    lines.append("")
    return "\n".join(lines)


def _fmt(value) -> str:
    if value is None:
        return "-"
    if isinstance(value, float):
        return f"{value:.1f}"
    return str(value)
