"""Replay analytics reporting.

Renders the aggregate analytics report (Markdown + JSON), the gap-
analysis Markdown, the trends Markdown, and the per-incident
analytics report. All renderers are pure: they consume the
data-model values produced by the loader, coverage, scoring,
trends, and review-audit modules.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Iterable, Optional

from app.replay_analytics.coverage import ReplayCoverageReport
from app.replay_analytics.loader import LoadedReplayBundle
from app.replay_analytics.models import (
    ANALYTICS_CERTIFICATION_DISCLAIMER,
    ReplayGap,
    ReplayQualityScore,
    ReplayRecommendation,
    ReplayTrend,
    ReviewAudit,
)
from app.replay_analytics.scoring import quality_bucket


def render_per_incident_report_md(
    *,
    bundle: LoadedReplayBundle,
    coverage: ReplayCoverageReport,
    score: ReplayQualityScore,
    audit: ReviewAudit,
    gaps: list[ReplayGap],
    recommendations: list[ReplayRecommendation],
) -> str:
    lines: list[str] = []
    lines.append(f"# Replay Analytics — `{bundle.incident_id}`")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/analyze_replay_coverage.py`. "
        "The platform is **not safety-certified**; this report is "
        "engineering analytics material._"
    )
    lines.append("")
    lines.append(f"- **Quality score:** {score.score}")
    lines.append(f"- **Coverage status:** `{score.coverage_status.value}`")
    lines.append(f"- **Confidence:** `{score.confidence}`")
    lines.append(f"- **Bag status:** `{bundle.bag_status}`")
    lines.append(f"- **Evidence origin:** `{bundle.evidence_origin}`")
    lines.append(f"- **Review status:** `{audit.status.value}`")
    lines.append("")
    lines.append("## Quality summary")
    lines.append("")
    lines.append(score.quality_summary)
    if score.blocking_gaps:
        lines.append("")
        lines.append("**Blocking gaps:** " + ", ".join(
            f"`{g}`" for g in score.blocking_gaps
        ))
    lines.append("")

    lines.append("## Coverage metrics")
    lines.append("")
    lines.append("| Metric | Value | Available | Detail |")
    lines.append("|---|---|---|---|")
    for m in coverage.metrics:
        value = "-" if m.value is None else (
            f"{m.value:.1f}" if isinstance(m.value, float) else str(m.value)
        )
        lines.append(
            f"| `{m.name}` | {value} | {'yes' if m.available else 'no'} | "
            f"{m.detail or '-'} |"
        )
    lines.append("")

    lines.append("## Gaps")
    lines.append("")
    if not gaps:
        lines.append("_No gaps detected._")
    else:
        lines.append("| Label | Severity | Detail |")
        lines.append("|---|---|---|")
        for g in gaps:
            lines.append(
                f"| `{g.label}` | `{g.severity.value}` | {g.detail} |"
            )
    lines.append("")

    lines.append("## Recommendations")
    lines.append("")
    if not recommendations:
        lines.append("_No recommendations._")
    else:
        for r in recommendations:
            lines.append(f"- **`{r.label}`** — {r.detail}")
    lines.append("")

    lines.append("## Review audit")
    lines.append("")
    lines.append(f"- Status: `{audit.status.value}`")
    if audit.operator:
        lines.append(f"- Operator: {audit.operator}")
    if audit.notes:
        lines.append(f"- Notes: {audit.notes}")
    if audit.audit_path:
        lines.append(f"- Audit source: `{audit.audit_path}`")
    lines.append("")
    if audit.completed_steps:
        lines.append("**Completed steps:**")
        for step in audit.completed_steps:
            lines.append(f"- `{step}`")
        lines.append("")
    if audit.pending_steps:
        lines.append("**Pending steps:**")
        for step in audit.pending_steps:
            lines.append(f"- `{step}`")
        lines.append("")

    lines.append("## Certification disclaimer")
    lines.append("")
    lines.append(ANALYTICS_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_aggregate_report_md(
    *,
    bundles: Iterable[LoadedReplayBundle],
    coverages: dict,
    scores: dict,
    audits: dict,
    trend: ReplayTrend,
    recommendations_by_incident: dict,
) -> str:
    bundles = list(bundles)
    bag_distribution = trend.bag_status_distribution
    coverage_distribution = trend.coverage_status_distribution
    review_distribution = trend.review_completion_distribution
    origin_distribution = trend.evidence_origin_distribution
    bucket_distribution = trend.quality_score_buckets

    sorted_scores = sorted(
        scores.values(), key=lambda s: (-s.score, s.incident_id)
    )
    highest = sorted_scores[:3]
    lowest = sorted(
        scores.values(), key=lambda s: (s.score, s.incident_id)
    )[:3]

    lines: list[str] = []
    lines.append("# Replay Analytics Report")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/generate_replay_analytics.py`. "
        "The platform is **not safety-certified**; this report is "
        "engineering analytics material._"
    )
    lines.append("")
    lines.append(f"- **Incidents analysed:** {len(bundles)}")
    lines.append("")

    lines.append("## Distributions")
    lines.append("")
    for title, distribution in (
        ("Bag status", bag_distribution),
        ("Coverage status", coverage_distribution),
        ("Review completion", review_distribution),
        ("Evidence origin", origin_distribution),
        ("Quality score buckets", bucket_distribution),
    ):
        lines.append(f"### {title}")
        lines.append("")
        if not distribution:
            lines.append("_No data._")
            lines.append("")
            continue
        lines.append("| Value | Count |")
        lines.append("|---|---|")
        for key in sorted(distribution):
            lines.append(f"| `{key}` | {distribution[key]} |")
        lines.append("")

    lines.append("## Highest-quality bundles")
    lines.append("")
    if not highest:
        lines.append("_None._")
    else:
        lines.append("| Incident | Score | Coverage | Confidence | Origin |")
        lines.append("|---|---|---|---|---|")
        for s in highest:
            origin = (
                bundles_by_id(bundles).get(s.incident_id).evidence_origin
                if bundles_by_id(bundles).get(s.incident_id)
                else "unknown"
            )
            lines.append(
                f"| `{s.incident_id}` | {s.score} | "
                f"`{s.coverage_status.value}` | `{s.confidence}` | "
                f"`{origin}` |"
            )
    lines.append("")

    lines.append("## Lowest-quality bundles")
    lines.append("")
    if not lowest:
        lines.append("_None._")
    else:
        lines.append("| Incident | Score | Coverage | Blocking gaps |")
        lines.append("|---|---|---|---|")
        for s in lowest:
            gaps = ", ".join(s.blocking_gaps[:3]) or "-"
            lines.append(
                f"| `{s.incident_id}` | {s.score} | "
                f"`{s.coverage_status.value}` | {gaps} |"
            )
    lines.append("")

    lines.append("## Trend tables")
    lines.append("")
    for title, items in (
        ("Most common safety states", trend.most_common_safety_states),
        ("Most common outcomes", trend.most_common_outcomes),
        ("Most common missing topics", trend.most_common_missing_topics),
        ("Most common gaps", trend.most_common_gaps),
    ):
        lines.append(f"### {title}")
        lines.append("")
        if not items:
            lines.append("_No data._")
            lines.append("")
            continue
        lines.append("| Value | Count |")
        lines.append("|---|---|")
        for label, count in items:
            lines.append(f"| `{label}` | {count} |")
        lines.append("")

    lines.append("## Recommendations summary")
    lines.append("")
    rec_counter: Counter[str] = Counter()
    for recs in recommendations_by_incident.values():
        for r in recs:
            rec_counter[r.label] += 1
    if not rec_counter:
        lines.append("_No recommendations._")
    else:
        lines.append("| Recommendation | Incidents |")
        lines.append("|---|---|")
        for label, count in sorted(
            rec_counter.items(), key=lambda kv: (-kv[1], kv[0])
        ):
            lines.append(f"| `{label}` | {count} |")
    lines.append("")

    lines.append("## Certification disclaimer")
    lines.append("")
    lines.append(ANALYTICS_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_gap_analysis_md(
    *, gaps_by_incident: dict[str, list[ReplayGap]]
) -> str:
    lines: list[str] = []
    lines.append("# Replay Gap Analysis")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/generate_replay_analytics.py`. "
        "The platform is **not safety-certified**._"
    )
    lines.append("")
    if not gaps_by_incident:
        lines.append("_No gaps detected._")
        lines.append("")
        return "\n".join(lines)
    severity_counter: Counter[str] = Counter()
    for gaps in gaps_by_incident.values():
        for g in gaps:
            severity_counter[g.severity.value] += 1
    lines.append("## Gap severity distribution")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in ("critical", "high", "moderate", "low", "informational"):
        lines.append(f"| `{sev}` | {severity_counter.get(sev, 0)} |")
    lines.append("")
    lines.append("## Gaps by incident")
    lines.append("")
    for incident_id in sorted(gaps_by_incident):
        lines.append(f"### `{incident_id}`")
        lines.append("")
        gaps = gaps_by_incident[incident_id]
        if not gaps:
            lines.append("_No gaps._")
            lines.append("")
            continue
        lines.append("| Label | Severity | Detail |")
        lines.append("|---|---|---|")
        for g in gaps:
            lines.append(
                f"| `{g.label}` | `{g.severity.value}` | {g.detail} |"
            )
        lines.append("")
    return "\n".join(lines)


def render_trends_md(trend: ReplayTrend) -> str:
    lines: list[str] = []
    lines.append("# Replay Trends")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/generate_replay_analytics.py`. "
        "The platform is **not safety-certified**._"
    )
    lines.append("")
    lines.append(f"- **Incident count:** {trend.incident_count}")
    lines.append("")
    for title, distribution in (
        ("Bag status distribution", trend.bag_status_distribution),
        ("Coverage status distribution", trend.coverage_status_distribution),
        (
            "Review completion distribution",
            trend.review_completion_distribution,
        ),
        ("Evidence origin distribution", trend.evidence_origin_distribution),
        ("Quality score buckets", trend.quality_score_buckets),
    ):
        lines.append(f"## {title}")
        lines.append("")
        if not distribution:
            lines.append("_No data._")
            lines.append("")
            continue
        lines.append("| Value | Count |")
        lines.append("|---|---|")
        for key in sorted(distribution):
            lines.append(f"| `{key}` | {distribution[key]} |")
        lines.append("")
    if trend.notes:
        lines.append("## Notes")
        lines.append("")
        for note in trend.notes:
            lines.append(f"- {note}")
        lines.append("")
    return "\n".join(lines)


def render_quality_index_json(
    *,
    bundles: Iterable[LoadedReplayBundle],
    scores: dict,
    coverages: dict,
) -> dict:
    out: list[dict] = []
    for bundle in bundles:
        score = scores.get(bundle.incident_id)
        cov = coverages.get(bundle.incident_id)
        out.append(
            {
                "incident_id": bundle.incident_id,
                "scenario_id": (
                    bundle.incident_report.get("scenario_id")
                    if bundle.incident_report
                    else None
                ),
                "score": score.score if score else 0,
                "coverage_status": (
                    cov.coverage_status.value if cov else "missing"
                ),
                "bag_status": bundle.bag_status,
                "evidence_origin": bundle.evidence_origin,
                "bucket": quality_bucket(score.score if score else 0),
            }
        )
    out.sort(key=lambda r: (-int(r["score"]), r["incident_id"]))
    return {"rows": out}


def bundles_by_id(bundles: Iterable[LoadedReplayBundle]) -> dict:
    return {b.incident_id: b for b in bundles}
