"""Operator review completion audit.

The review audit module never infers completion. Completion is
recognised only via an explicit ``review-audit.json`` artefact that
declares which steps the operator has acknowledged. If the file is
absent the audit reports ``not_started``.

The expected schema for ``review-audit.json``:

    {
      "incident_id": "<id>",
      "operator": "<name or label>",
      "completed_steps": ["bag_status_reviewed", "..."],
      "status_override": "completed" | "partial" | "not_started",
      "notes": "<free text>"
    }

``status_override`` is optional. When absent the audit infers status
from ``completed_steps`` against the canonical checklist:

* zero completed -> ``not_started``
* every step completed -> ``completed``
* otherwise -> ``partial``

The canonical checklist mirrors the operator checklist surfaced by
the Phase-7 ``replay-review-report.md``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from app.replay_analytics.loader import LoadedReplayBundle
from app.replay_analytics.models import (
    ReviewAudit,
    ReviewCompletionStatus,
)


CANONICAL_REVIEW_STEPS: tuple[str, ...] = (
    "bag_status_reviewed",
    "missing_topics_reviewed",
    "markers_loaded",
    "safety_state_matches_report",
    "cmd_vel_arbitration_matches_audit",
    "replay_integrity_checked",
    "discrepancies_recorded_outside_bundle",
)


def audit_review(bundle: LoadedReplayBundle) -> ReviewAudit:
    """Audit operator review completion for ``bundle``.

    Reads ``review-audit.json`` from the bundle directory when
    present. The function never infers completion from any other
    artefact (no "the report is rendered, therefore it was reviewed"
    shortcuts).
    """

    incident_id = bundle.incident_id
    payload = bundle.review_audit
    if payload is None:
        return ReviewAudit(
            incident_id=incident_id,
            status=ReviewCompletionStatus.NOT_STARTED,
            completed_steps=(),
            pending_steps=tuple(CANONICAL_REVIEW_STEPS),
            audit_path="",
        )
    if not isinstance(payload, dict):
        return ReviewAudit(
            incident_id=incident_id,
            status=ReviewCompletionStatus.INCONCLUSIVE,
            completed_steps=(),
            pending_steps=tuple(CANONICAL_REVIEW_STEPS),
            notes="review-audit.json has unexpected shape",
            audit_path=str(bundle.incident_dir / "review-audit.json"),
        )

    declared_completed = payload.get("completed_steps") or []
    if not isinstance(declared_completed, list):
        declared_completed = []
    completed = tuple(
        step for step in declared_completed
        if isinstance(step, str) and step in CANONICAL_REVIEW_STEPS
    )
    pending = tuple(s for s in CANONICAL_REVIEW_STEPS if s not in completed)

    explicit = payload.get("status_override")
    if isinstance(explicit, str):
        try:
            status = ReviewCompletionStatus(explicit)
        except ValueError:
            status = ReviewCompletionStatus.INCONCLUSIVE
    else:
        if not completed:
            status = ReviewCompletionStatus.NOT_STARTED
        elif not pending:
            status = ReviewCompletionStatus.COMPLETED
        else:
            status = ReviewCompletionStatus.PARTIAL

    return ReviewAudit(
        incident_id=incident_id,
        status=status,
        completed_steps=completed,
        pending_steps=pending,
        operator=str(payload.get("operator", "")),
        notes=str(payload.get("notes", "")),
        audit_path=str(bundle.incident_dir / "review-audit.json"),
    )


def write_review_audit_md(audit: ReviewAudit, *, path: Path) -> None:
    """Write a Markdown summary of the audit (for human review)."""

    lines: list[str] = []
    lines.append(f"# Review Audit — `{audit.incident_id}`")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/audit_replay_reviews.py`. The "
        "platform is **not safety-certified**; the audit is "
        "engineering analytics material._"
    )
    lines.append("")
    lines.append(f"- **Status:** `{audit.status.value}`")
    if audit.operator:
        lines.append(f"- **Operator:** {audit.operator}")
    if audit.audit_path:
        lines.append(f"- **Audit source:** `{audit.audit_path}`")
    lines.append("")
    lines.append("## Steps")
    lines.append("")
    lines.append("| Step | State |")
    lines.append("|---|---|")
    for step in CANONICAL_REVIEW_STEPS:
        state = "completed" if step in audit.completed_steps else "pending"
        lines.append(f"| `{step}` | `{state}` |")
    if audit.notes:
        lines.append("")
        lines.append("## Notes")
        lines.append("")
        lines.append(audit.notes)
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_review_audit_json(audit: ReviewAudit, *, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(audit.as_dict(), indent=2, sort_keys=True),
        encoding="utf-8",
    )
