"""Replay review report renderer.

Produces ``replay-review-report.{md,json}`` from the manifest +
validation results + Foxglove session + markers. The report carries
the verbatim certification disclaimer.
"""

from __future__ import annotations

from datetime import datetime, timezone

from app.replay_review.models import (
    REPLAY_CERTIFICATION_DISCLAIMER,
    FoxgloveSession,
    ReplayEvidenceOrigin,
    ReplayExecutionStatus,
    ReplayMarker,
    ReplayReviewManifest,
    ReplayReviewReport,
    ReplayValidationResult,
)


def _evidence_origin_for(
    *,
    manifest: ReplayReviewManifest,
) -> ReplayEvidenceOrigin:
    """Pick the evidence_origin that best describes the manifest."""

    if manifest.bag_status == ReplayExecutionStatus.READY:
        return ReplayEvidenceOrigin.BAG_BACKED
    if manifest.bag_status == ReplayExecutionStatus.PARTIAL:
        # Some bag artefacts but not enough for full replay; still
        # bag-backed in origin, but the report calls out the gap.
        return ReplayEvidenceOrigin.BAG_BACKED
    if manifest.evidence_status == "static_only":
        return ReplayEvidenceOrigin.SCENARIO_EVIDENCE
    if manifest.evidence_status in {"complete", "partial"}:
        return ReplayEvidenceOrigin.SCENARIO_EVIDENCE
    if manifest.evidence_status == "live_runtime":
        return ReplayEvidenceOrigin.LIVE_RUNTIME
    return ReplayEvidenceOrigin.UNKNOWN


_DEFAULT_REVIEW_WORKFLOW: tuple[str, ...] = (
    "Confirm the incident bundle is current (re-run reconstruct_incident.py if needed).",
    "Inspect bag_status and missing_topics in this report.",
    "If bag_status is ready or partial, open the bag in Foxglove with the canonical layout.",
    "Use timeline_markers to align the playhead to first_fault, first_safety_transition, "
    "first_command_intervention, and the terminal entry.",
    "Compare the safety state and cmd_vel plots against the incident report's claims.",
    "Record any discrepancy in a separate document; do not mutate the incident bundle.",
)


_DEFAULT_OPERATOR_CHECKLIST: tuple[str, ...] = (
    "[ ] Bag status reviewed",
    "[ ] Missing topics reviewed",
    "[ ] Markers loaded into the Foxglove timeline",
    "[ ] Safety state matches incident-report.md",
    "[ ] cmd_vel arbitration matches command-audit.json",
    "[ ] Replay integrity checked",
    "[ ] Discrepancies recorded outside the incident bundle",
)


def build_report(
    *,
    manifest: ReplayReviewManifest,
    session: FoxgloveSession,
    markers: tuple[ReplayMarker, ...],
    validations: tuple[ReplayValidationResult, ...],
    replay_execution_status: ReplayExecutionStatus,
) -> ReplayReviewReport:
    return ReplayReviewReport(
        incident_id=manifest.incident_id,
        run_id=manifest.run_id,
        scenario_id=manifest.scenario_id,
        bag_status=manifest.bag_status,
        replay_execution_status=replay_execution_status,
        evidence_origin=_evidence_origin_for(manifest=manifest),
        expected_topics=tuple(t.name for t in manifest.expected_topics),
        available_topics=manifest.available_topics,
        missing_topics=manifest.missing_topics,
        timeline_markers=markers,
        foxglove_layout_path=manifest.foxglove_layout_path,
        foxglove_session_path=manifest.foxglove_session_path,
        review_workflow=_DEFAULT_REVIEW_WORKFLOW,
        known_limitations=manifest.known_limitations,
        validation_results=validations,
        operator_checklist=_DEFAULT_OPERATOR_CHECKLIST,
        generated_at_utc=datetime.now(tz=timezone.utc).isoformat(timespec="seconds"),
    )


def render_report_md(report: ReplayReviewReport) -> str:
    counts = report.status_counts()
    lines: list[str] = []
    lines.append(f"# Replay Review Report — `{report.incident_id}`")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/build_replay_review_bundle.py`. "
        "The platform is **not safety-certified**; this report is "
        "engineering analysis material._"
    )
    lines.append("")
    lines.append(f"- **Run id:** `{report.run_id or '-'}`")
    lines.append(f"- **Scenario id:** `{report.scenario_id or '-'}`")
    lines.append(f"- **Bag status:** `{report.bag_status.value}`")
    lines.append(
        f"- **Replay execution status:** `{report.replay_execution_status.value}`"
    )
    lines.append(f"- **Evidence origin:** `{report.evidence_origin.value}`")
    lines.append(f"- **Foxglove layout:** `{report.foxglove_layout_path}`")
    lines.append(f"- **Foxglove session:** `{report.foxglove_session_path}`")
    lines.append(f"- **Markers:** {len(report.timeline_markers)}")
    lines.append(f"- **Generated:** {report.generated_at_utc}")
    lines.append("")

    lines.append("## Validation results")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|---|---|")
    for status, count in counts.items():
        lines.append(f"| `{status}` | {count} |")
    lines.append("")
    lines.append("| Check | Status | Detail |")
    lines.append("|---|---|---|")
    for v in report.validation_results:
        lines.append(
            f"| `{v.name}` | `{v.status.value}` | {v.detail or '-'} |"
        )
        if v.reason:
            lines.append(f"|   _reason_ |   | {v.reason} |")
    lines.append("")

    lines.append("## Expected topics")
    lines.append("")
    expected_set = set(report.expected_topics)
    available_set = set(report.available_topics)
    if not report.available_topics:
        lines.append(
            "_Bag inventory not available; topic coverage cannot be verified._"
        )
    else:
        lines.append("| Topic | Present in bag |")
        lines.append("|---|---|")
        for topic in report.expected_topics:
            lines.append(
                f"| `{topic}` | {'yes' if topic in available_set else 'no'} |"
            )
    lines.append("")
    if report.missing_topics:
        lines.append("**Missing required topics:**")
        for name in report.missing_topics:
            lines.append(f"- `{name}`")
        lines.append("")

    lines.append("## Timeline markers")
    lines.append("")
    if not report.timeline_markers:
        lines.append("_No markers emitted from the incident timeline._")
    else:
        lines.append(
            "| Marker | Label | Timeline # | Sim time (ns) | Rel (ms) | Alignment | Confidence | Origin |"
        )
        lines.append("|---|---|---|---|---|---|---|---|")
        for m in report.timeline_markers:
            lines.append(
                f"| `{m.marker_id}` | {m.label} | {m.timeline_index} | "
                f"{m.sim_time_ns if m.sim_time_ns is not None else '-'} | "
                f"{m.relative_time_ms if m.relative_time_ms is not None else '-'} | "
                f"`{m.alignment}` | `{m.confidence}` | `{m.evidence_origin.value}` |"
            )
    lines.append("")

    lines.append("## Review workflow")
    lines.append("")
    for step in report.review_workflow:
        lines.append(f"- {step}")
    lines.append("")

    lines.append("## Operator checklist")
    lines.append("")
    for line in report.operator_checklist:
        lines.append(f"- {line}")
    lines.append("")

    lines.append("## Known limitations")
    lines.append("")
    for line in report.known_limitations:
        lines.append(f"- {line}")
    lines.append("")

    lines.append("## Certification disclaimer")
    lines.append("")
    lines.append(REPLAY_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)
