"""Render the registry + hydration report as Markdown."""

from __future__ import annotations

from .models import (
    INTEGRITY_FAILED,
    INTEGRITY_MISSING,
    INTEGRITY_PARTIAL,
    INTEGRITY_PASSED,
    ArtifactRegistry,
    HydrationReport,
)


_INTEGRITY_BADGE: dict[str, str] = {
    INTEGRITY_PASSED: "✅ passed",
    INTEGRITY_PARTIAL: "⚠️ partial",
    INTEGRITY_FAILED: "❌ failed",
    INTEGRITY_MISSING: "🚫 missing",
    "unverified": "⏸ unverified",
}


def render_registry_markdown(registry: ArtifactRegistry) -> str:
    lines: list[str] = []
    lines.append("# Canonical artefact registry")
    lines.append("")
    lines.append(
        "This file lists every committed replay artefact the platform "
        "is allowed to render. It is regenerated by "
        "`tools/hydrate_replay_artifacts.py`."
    )
    lines.append("")
    lines.append(f"- **Schema version:** `{registry.schema_version}`")
    lines.append(f"- **Generated at (UTC):** `{registry.generated_at_utc}`")
    lines.append(f"- **Artefact root:** `{registry.artefact_root}`")
    lines.append(f"- **Records:** {len(registry.records)}")
    lines.append("")
    if not registry.records:
        lines.append("No artefacts registered. The frontend will fall "
                     "back to bounded-inputs maps for every mission.")
        lines.append("")
        return "\n".join(lines)
    lines.append("| run_id | kind | derivation_source | bag_status | "
                 "lifecycle | integrity | files |")
    lines.append("|---|---|---|---|---|---|---:|")
    for r in registry.records:
        badge = _INTEGRITY_BADGE.get(r.integrity, r.integrity)
        lines.append(
            f"| `{r.run_id}` | {r.kind} | `{r.derivation_source}` | "
            f"`{r.bag_status}` | `{r.lifecycle}` | {badge} | "
            f"{len(r.files)} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_hydration_markdown(report: HydrationReport) -> str:
    lines: list[str] = []
    lines.append("# Hydration report")
    lines.append("")
    lines.append(
        "Generated by `tools/hydrate_replay_artifacts.py`. The report "
        "is honest: a failing hydration NEVER rewrites the canonical "
        "registry."
    )
    lines.append("")
    lines.append(f"- **Generated at (UTC):** `{report.generated_at_utc}`")
    lines.append(f"- **Registry path:** `{report.registry_path}`")
    lines.append(
        f"- **Overall integrity:** "
        f"{_INTEGRITY_BADGE.get(report.overall_integrity, report.overall_integrity)}"
    )
    lines.append("")
    if not report.outcomes:
        lines.append("No artefacts hydrated.")
        lines.append("")
        return "\n".join(lines)
    lines.append("| run_id | rebuilt | integrity | drift |")
    lines.append("|---|:---:|---|---|")
    for o in report.outcomes:
        drift = "; ".join(o.drift) if o.drift else "—"
        lines.append(
            f"| `{o.run_id}` | {'✓' if o.rebuilt else '×'} | "
            f"{_INTEGRITY_BADGE.get(o.integrity, o.integrity)} | {drift} |"
        )
    lines.append("")
    return "\n".join(lines)


__all__ = [
    "render_hydration_markdown",
    "render_registry_markdown",
]
