"""Render the runtime validation report.

Two outputs:

* a JSON manifest under
  ``evidence/runtime/<run_id>/runtime-validation.json``;
* a Markdown report under
  ``evidence/runtime/<run_id>/runtime-validation.md`` (and optionally
  ``docs/RUNTIME_VALIDATION_REPORT.md`` for the canonical version).

The renderer never invents results. Every check in
:class:`RuntimeReport` carries a status from the Phase-3 vocabulary;
``not_executed`` carries an explicit ``reason``. The known-limitations
section is included verbatim.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Iterable

from app.verification.acceptance import AcceptanceStatus, aggregate_status


_DEFAULT_KNOWN_LIMITATIONS: tuple[str, ...] = (
    "The platform is **not** safety-certified. This report demonstrates "
    "engineering verification discipline, not regulatory compliance.",
    "Live ROS 2 / Gazebo evidence is collected only on a Jazzy host. "
    "Runs in environments that lack rclpy / Gazebo Harmonic surface "
    "their checks as `not_executed` with a reason; never as `passed`.",
    "Static-only mode validates the workspace artefacts (launch files, "
    "URDF, bridge YAML, node modules). It does not exercise the safety "
    "bridge against a live actuator stream.",
    "Closed-loop verification of the Nav2 velocity-clamp boundary "
    "requires a Jazzy host. The static-only path asserts the boundary "
    "at the source level only.",
)


@dataclass
class RuntimeCheck:
    name: str
    status: AcceptanceStatus
    detail: str = ""
    reason: str = ""
    """Populated when status is ``skipped`` or ``not_executed``."""

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    evidence_paths: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "name": self.name,
            "status": self.status.value,
            "detail": self.detail,
            "reason": self.reason,
            "errors": list(self.errors),
            "warnings": list(self.warnings),
            "evidence_paths": list(self.evidence_paths),
        }


@dataclass
class RuntimeReport:
    run_id: str
    mode: str
    """One of ``live``, ``static-only``, ``mixed``."""

    generated_at_utc: str = ""
    environment: dict[str, str] = field(default_factory=dict)
    checks: list[RuntimeCheck] = field(default_factory=list)
    known_limitations: tuple[str, ...] = field(
        default_factory=lambda: _DEFAULT_KNOWN_LIMITATIONS
    )

    def __post_init__(self) -> None:
        if not self.generated_at_utc:
            self.generated_at_utc = datetime.now(tz=timezone.utc).isoformat(
                timespec="seconds"
            )

    @property
    def status(self) -> AcceptanceStatus:
        return aggregate_status(c.status for c in self.checks)

    def status_counts(self) -> dict[str, int]:
        out = {s.value: 0 for s in AcceptanceStatus}
        for c in self.checks:
            out[c.status.value] += 1
        return out

    def as_dict(self) -> dict:
        return {
            "run_id": self.run_id,
            "mode": self.mode,
            "generated_at_utc": self.generated_at_utc,
            "environment": dict(self.environment),
            "status": self.status.value,
            "status_counts": self.status_counts(),
            "checks": [c.as_dict() for c in self.checks],
            "known_limitations": list(self.known_limitations),
        }


def render_runtime_report_md(report: RuntimeReport) -> str:
    counts = report.status_counts()
    lines: list[str] = []
    lines.append("# Runtime Validation Report")
    lines.append("")
    lines.append(
        "_This report is generated by "
        "`rover_ws/tools/live_runtime_validator.py`. The platform is "
        "**not safety-certified**; this document demonstrates "
        "engineering verification discipline. Checks carry one of "
        "`passed`, `failed`, `partial`, `skipped`, or `not_executed`. "
        "A `not_executed` check requires a Jazzy host; never read it "
        "as a pass._"
    )
    lines.append("")
    lines.append(f"- **Run id:** `{report.run_id}`")
    lines.append(f"- **Mode:** `{report.mode}`")
    lines.append(f"- **Generated:** {report.generated_at_utc}")
    lines.append(f"- **Overall status:** `{report.status.value}`")
    lines.append("")
    if report.environment:
        lines.append("## Environment")
        lines.append("")
        lines.append("| Key | Value |")
        lines.append("|---|---|")
        for key, value in sorted(report.environment.items()):
            lines.append(f"| `{key}` | {value} |")
        lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|---|---|")
    for status in AcceptanceStatus:
        lines.append(f"| `{status.value}` | {counts[status.value]} |")
    lines.append("")
    lines.append("## Checks")
    lines.append("")
    lines.append("| Check | Status | Detail |")
    lines.append("|---|---|---|")
    for c in report.checks:
        lines.append(
            f"| `{c.name}` | `{c.status.value}` | {c.detail or '-'} |"
        )
        if c.status in {AcceptanceStatus.SKIPPED, AcceptanceStatus.NOT_EXECUTED} and c.reason:
            lines.append(f"|   _reason_ |   | {c.reason} |")
        for err in c.errors:
            lines.append(f"|   _error_ |   | {err} |")
        for warn in c.warnings:
            lines.append(f"|   _warning_ |   | {warn} |")
        for ev in c.evidence_paths:
            lines.append(f"|   _evidence_ |   | `{ev}` |")
    lines.append("")
    lines.append("## Known limitations")
    lines.append("")
    for line in report.known_limitations:
        lines.append(f"- {line}")
    lines.append("")
    return "\n".join(lines)


def render_known_limitations_md(report: RuntimeReport) -> str:
    """Stand-alone Markdown for ``known-limitations.md``."""

    lines: list[str] = []
    lines.append("# Known limitations")
    lines.append("")
    lines.append(f"Run id: `{report.run_id}`. Mode: `{report.mode}`.")
    lines.append("")
    for line in report.known_limitations:
        lines.append(f"- {line}")
    lines.append("")
    return "\n".join(lines)
