"""Scenario verification report generator.

Builds ``docs/SCENARIO_VERIFICATION_REPORT.md`` from a list of
:class:`ScenarioVerification` results. The report includes:

* a summary table by status,
* a per-scenario table with check-level detail,
* requirement coverage summary,
* failed checks list,
* known limitations.

The generator does not produce false positives. A scenario reported
as ``not_executed`` carries the reason; ``partial`` carries the list
of checks that did not run.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from app.verification.acceptance import AcceptanceStatus, aggregate_status
from app.verification.requirements import REQUIREMENTS, RequirementsRegistry
from app.verification.scenario_verifier import ScenarioVerification


_KNOWN_LIMITATIONS_DEFAULT: tuple[str, ...] = (
    "The platform is **not** safety-certified. This report demonstrates "
    "engineering verification discipline, not regulatory compliance.",
    "Scenarios run against the deterministic Python engine. End-to-end "
    "Gazebo / ROS 2 verification on a Jazzy host is documented in "
    "`rover_ws/tests/manual.md`; results from those runs are not "
    "captured automatically by this report.",
    "The wheel-slip-only scenario does not by itself reach "
    "`MISSION_DEGRADED` because the platform has no state estimator; "
    "the corresponding scenario combines slip with a co-occurring IMU "
    "bias to demonstrate the degraded mode honestly.",
    "Nav2 is integrated only via the velocity-clamp boundary node; "
    "full Nav2 lifecycle coverage is out of scope for Phase 3.",
)


@dataclass
class VerificationReport:
    verifications: tuple[ScenarioVerification, ...]
    generated_at_utc: str
    known_limitations: tuple[str, ...] = field(default_factory=lambda: _KNOWN_LIMITATIONS_DEFAULT)

    @property
    def overall_status(self) -> AcceptanceStatus:
        return aggregate_status(v.status for v in self.verifications)

    def status_counts(self) -> dict[str, int]:
        out = {s.value: 0 for s in AcceptanceStatus}
        for v in self.verifications:
            out[v.status.value] += 1
        return out

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at_utc": self.generated_at_utc,
            "overall_status": self.overall_status.value,
            "status_counts": self.status_counts(),
            "scenarios": [v.as_dict() for v in self.verifications],
            "known_limitations": list(self.known_limitations),
        }


def render_scenario_verification_report(
    verifications: Iterable[ScenarioVerification],
    *,
    known_limitations: tuple[str, ...] = _KNOWN_LIMITATIONS_DEFAULT,
    generated_at_utc: str | None = None,
    registry: RequirementsRegistry | None = None,
) -> str:
    """Return the report Markdown."""

    if generated_at_utc is None:
        generated_at_utc = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")
    verifications = tuple(verifications)
    registry = registry or RequirementsRegistry(REQUIREMENTS)

    report = VerificationReport(
        verifications=verifications,
        generated_at_utc=generated_at_utc,
        known_limitations=known_limitations,
    )
    counts = report.status_counts()

    lines: list[str] = []
    lines.append("# Scenario Verification Report")
    lines.append("")
    lines.append(
        "_Generated by `tools/generate_verification_report.py` from the "
        "deterministic engine. The platform is **not safety-certified**; "
        "this report demonstrates engineering verification discipline._"
    )
    lines.append("")
    lines.append(f"- **Generated:** {generated_at_utc}")
    lines.append(f"- **Overall status:** `{report.overall_status.value}`")
    lines.append(f"- **Scenarios verified:** {len(verifications)}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|---|---|")
    for status in AcceptanceStatus:
        lines.append(f"| `{status.value}` | {counts[status.value]} |")
    lines.append("")
    lines.append("## Scenarios")
    lines.append("")
    lines.append(
        "| Scenario | Status | Safety state | Mission state | "
        "Faults fired | Recovery | Run dir |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    for v in verifications:
        safety = v.final_safety_state.value if v.final_safety_state else "-"
        mission = v.final_mission_state or "-"
        faults = ", ".join(f"`{f}`" for f in v.fired_faults) or "-"
        run_dir = str(v.run_dir) if v.run_dir else "-"
        lines.append(
            f"| `{v.expectation.scenario_id}` | `{v.status.value}` | "
            f"`{safety}` | `{mission}` | {faults} | "
            f"{v.recovery_engagement_count} | `{run_dir}` |"
        )
    lines.append("")
    lines.append("## Per-scenario details")
    lines.append("")
    for v in verifications:
        lines.append(f"### `{v.expectation.scenario_id}`")
        lines.append("")
        lines.append(f"- **Status:** `{v.status.value}`")
        lines.append(f"- **Description:** {v.expectation.description}")
        if v.expectation.requirement_ids:
            lines.append(
                f"- **Requirements:** "
                + ", ".join(f"`{rid}`" for rid in v.expectation.requirement_ids)
            )
        if v.not_executed_reason:
            lines.append(f"- **Not executed reason:** {v.not_executed_reason}")
        lines.append("")
        lines.append("| Check | Status | Detail |")
        lines.append("|---|---|---|")
        for c in v.checks:
            lines.append(
                f"| `{c.name}` | `{c.status.value}` | {c.detail or '-'} |"
            )
            for err in c.errors:
                lines.append(f"|   _error_ |   | {err} |")
            for warn in c.warnings:
                lines.append(f"|   _warning_ |   | {warn} |")
        lines.append("")

    failed_checks = [
        (v, c)
        for v in verifications
        for c in v.checks
        if c.status == AcceptanceStatus.FAILED
    ]
    lines.append("## Failed checks")
    lines.append("")
    if not failed_checks:
        lines.append("_None._")
    else:
        lines.append("| Scenario | Check | Detail |")
        lines.append("|---|---|---|")
        for v, c in failed_checks:
            lines.append(
                f"| `{v.expectation.scenario_id}` | `{c.name}` | {c.detail} |"
            )
    lines.append("")

    lines.append("## Requirement coverage")
    lines.append("")
    by_scenario = {v.expectation.scenario_id: v for v in verifications}
    lines.append("| Requirement | Status | Scenarios |")
    lines.append("|---|---|---|")
    for req in registry:
        scenarios = [s for s in req.scenario_refs if s in by_scenario]
        statuses = [by_scenario[s].status for s in scenarios]
        if scenarios:
            agg = aggregate_status(statuses)
            scen_text = ", ".join(f"`{s}` (`{by_scenario[s].status.value}`)" for s in scenarios)
        elif req.test_refs:
            agg = AcceptanceStatus.PASSED
            scen_text = f"_test-level only_ ({len(req.test_refs)} test(s))"
        else:
            agg = AcceptanceStatus.NOT_EXECUTED
            scen_text = "_no scenario or test coverage_"
        lines.append(f"| `{req.req_id}` | `{agg.value}` | {scen_text} |")
    lines.append("")

    lines.append("## Known limitations")
    lines.append("")
    for line in known_limitations:
        lines.append(f"- {line}")
    lines.append("")
    return "\n".join(lines)
