"""Traceability matrix.

Combines the requirement registry, scenario expectations, and (when
provided) the latest scenario verification results into:

* a JSON manifest (``verification/traceability.json``),
* a Markdown table (``docs/TRACEABILITY_MATRIX.md``).

Each row links a requirement to:

* the architecture-doc references that justify it,
* the implementation modules that satisfy it,
* the scenarios that exercise it,
* the tests that assert it,
* the evidence artefacts produced when verification runs,
* the latest verification status.

Status values come from :class:`AcceptanceStatus`. When no
verification result is supplied, the row's status is
``not_executed`` to make the gap visible.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Optional

from app.verification.acceptance import AcceptanceStatus, aggregate_status
from app.verification.requirements import Requirement, RequirementsRegistry, REQUIREMENTS
from app.verification.scenario_verifier import (
    ScenarioVerification,
    SCENARIO_EXPECTATIONS,
)


@dataclass(frozen=True)
class TraceabilityRow:
    requirement: Requirement
    architecture_refs: tuple[str, ...]
    implementation_refs: tuple[str, ...]
    scenario_refs: tuple[str, ...]
    test_refs: tuple[str, ...]
    evidence_paths: tuple[str, ...]
    status: AcceptanceStatus
    status_detail: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "requirement_id": self.requirement.req_id,
            "kind": self.requirement.kind.value,
            "title": self.requirement.title,
            "architecture_refs": list(self.architecture_refs),
            "implementation_refs": list(self.implementation_refs),
            "scenario_refs": list(self.scenario_refs),
            "test_refs": list(self.test_refs),
            "evidence_paths": list(self.evidence_paths),
            "status": self.status.value,
            "status_detail": self.status_detail,
        }


@dataclass
class TraceabilityMatrix:
    rows: tuple[TraceabilityRow, ...]
    generated_at_utc: str

    @property
    def overall_status(self) -> AcceptanceStatus:
        return aggregate_status(r.status for r in self.rows)

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at_utc": self.generated_at_utc,
            "overall_status": self.overall_status.value,
            "row_count": len(self.rows),
            "rows": [r.as_dict() for r in self.rows],
        }

    def render_markdown(self) -> str:
        lines: list[str] = []
        lines.append("# Traceability Matrix")
        lines.append("")
        lines.append(
            "_This matrix is generated by "
            "`tools/generate_traceability.py` from the requirements "
            "registry in `backend/app/verification/requirements.py` and "
            "the latest scenario verification run. The platform is "
            "**not safety-certified**; this matrix demonstrates "
            "traceability discipline for portfolio and engineering "
            "learning purposes._"
        )
        lines.append("")
        lines.append(f"- **Generated:** {self.generated_at_utc}")
        lines.append(f"- **Overall status:** `{self.overall_status.value}`")
        lines.append(f"- **Requirements covered:** {len(self.rows)}")
        lines.append("")
        lines.append(
            "| Req ID | Title | Architecture | Implementation | Scenarios | Tests | Evidence | Status |"
        )
        lines.append("|---|---|---|---|---|---|---|---|")
        for r in self.rows:
            arch = "<br/>".join(f"`{a}`" for a in r.architecture_refs) or "-"
            impl = "<br/>".join(f"`{a}`" for a in r.implementation_refs) or "-"
            scen = "<br/>".join(f"`{a}`" for a in r.scenario_refs) or "-"
            tests = "<br/>".join(f"`{a}`" for a in r.test_refs) or "-"
            evid = "<br/>".join(f"`{a}`" for a in r.evidence_paths) or "-"
            lines.append(
                f"| `{r.requirement.req_id}` | {r.requirement.title} | {arch} | {impl} | "
                f"{scen} | {tests} | {evid} | `{r.status.value}` |"
            )
        lines.append("")
        lines.append("## Requirement coverage notes")
        lines.append("")
        for r in self.rows:
            if r.status_detail:
                lines.append(f"- `{r.requirement.req_id}` — {r.status_detail}")
        lines.append("")
        return "\n".join(lines)


def build_traceability_matrix(
    *,
    registry: RequirementsRegistry | None = None,
    verifications: Iterable[ScenarioVerification] | None = None,
    evidence_root: Path | str | None = None,
    generated_at_utc: Optional[str] = None,
) -> TraceabilityMatrix:
    """Compose the matrix from registry + (optional) verification results."""

    from datetime import datetime, timezone

    registry = registry or RequirementsRegistry(REQUIREMENTS)
    verifications = list(verifications or [])
    by_scenario_id: dict[str, ScenarioVerification] = {
        v.expectation.scenario_id: v for v in verifications
    }
    rows: list[TraceabilityRow] = []
    evidence_root_path = Path(evidence_root) if evidence_root else None

    for req in registry:
        # Aggregate the statuses of the scenarios that exercise this
        # requirement. If no scenario covers it, the status reflects
        # whether it has tests but no scenario.
        relevant = [
            by_scenario_id.get(sid)
            for sid in req.scenario_refs
            if sid in by_scenario_id
        ]
        relevant_statuses = [v.status for v in relevant if v is not None]
        if relevant_statuses:
            status = aggregate_status(relevant_statuses)
            failures = [v for v in relevant if v and v.status == AcceptanceStatus.FAILED]
            if failures:
                detail = "; ".join(
                    f"{v.expectation.scenario_id}: {next((c.detail for c in v.checks if c.status == AcceptanceStatus.FAILED), '?')}"
                    for v in failures
                )
            else:
                detail = (
                    f"{len(relevant)} scenario(s) verified" if relevant else "no scenario coverage"
                )
        elif req.scenario_refs:
            status = AcceptanceStatus.NOT_EXECUTED
            detail = (
                "scenario(s) declared but no verification result supplied: "
                + ", ".join(req.scenario_refs)
            )
        else:
            # Requirement has only test-level coverage (e.g. unit
            # invariants like REQ-DIAG-001). Status reflects test
            # coverage presence rather than a scenario run.
            status = (
                AcceptanceStatus.PASSED
                if req.test_refs
                else AcceptanceStatus.NOT_EXECUTED
            )
            detail = (
                f"covered by {len(req.test_refs)} test(s)"
                if req.test_refs
                else "no test or scenario coverage"
            )

        evidence_paths: list[str] = []
        if evidence_root_path is not None:
            for sid in req.scenario_refs:
                candidate = evidence_root_path / "scenarios" / sid / "evidence.json"
                if candidate.exists():
                    evidence_paths.append(str(candidate))

        rows.append(
            TraceabilityRow(
                requirement=req,
                architecture_refs=req.architecture_refs,
                implementation_refs=req.implementation_refs,
                scenario_refs=req.scenario_refs,
                test_refs=req.test_refs,
                evidence_paths=tuple(evidence_paths),
                status=status,
                status_detail=detail,
            )
        )

    if generated_at_utc is None:
        generated_at_utc = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")
    return TraceabilityMatrix(rows=tuple(rows), generated_at_utc=generated_at_utc)


def write_traceability(
    matrix: TraceabilityMatrix,
    *,
    json_path: Path | str,
    markdown_path: Path | str | None = None,
) -> None:
    """Persist the matrix as JSON + (optional) Markdown."""

    json_path = Path(json_path)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(matrix.to_dict(), indent=2, sort_keys=True), encoding="utf-8")
    if markdown_path is not None:
        markdown_path = Path(markdown_path)
        markdown_path.parent.mkdir(parents=True, exist_ok=True)
        markdown_path.write_text(matrix.render_markdown(), encoding="utf-8")
