"""Reviewer-summary Markdown writer + bundle orchestrator.

The orchestrator wires the loader, schema writer, exporters,
manifest writer, notebook builder, and reporter into a single
:class:`ReviewerExport`. The orchestrator is deterministic; the
caller supplies the export id (CI passes a stamped id; tests use a
fixture).
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Optional

from app.reviewer_exports.exporters import (
    build_table_rows,
    write_csv,
    write_jsonl,
)
from app.reviewer_exports.loader import load_reviewer_inputs
from app.reviewer_exports.manifest import (
    manifest_source_artifacts,
    write_manifest,
)
from app.reviewer_exports.models import (
    ALL_TABLES,
    DEFAULT_KNOWN_LIMITATIONS,
    LoadedReviewerInputs,
    REVIEWER_EXPORT_DISCLAIMER,
    ReviewerExport,
    TABLE_FIELDS,
    TableExport,
)
from app.reviewer_exports.notebook import write_notebook, write_readme
from app.reviewer_exports.schema import write_all_schemas


def build_reviewer_export(
    *,
    bundle_dir: Path,
    programme_review_root: Optional[Path] = None,
    incidents_root: Optional[Path] = None,
    reliability_impact_root: Optional[Path] = None,
    traceability_path: Optional[Path] = None,
    export_id: Optional[str] = None,
    generated_at_utc: Optional[str] = None,
) -> ReviewerExport:
    """Build the full reviewer-export bundle on disk."""

    inputs = load_reviewer_inputs(
        programme_review_root=programme_review_root,
        incidents_root=incidents_root,
        reliability_impact_root=reliability_impact_root,
        traceability_path=traceability_path,
    )

    bundle_dir.mkdir(parents=True, exist_ok=True)
    schemas_dir = bundle_dir / "schemas"
    csv_dir = bundle_dir / "csv"
    jsonl_dir = bundle_dir / "jsonl"
    notebooks_dir = bundle_dir / "notebooks"

    schema_paths = write_all_schemas(schemas_dir=schemas_dir)
    tables: list[TableExport] = []
    for table in ALL_TABLES:
        rows = build_table_rows(table, inputs)
        csv_path = write_csv(table, rows, path=csv_dir / f"{table}.csv")
        jsonl_path = write_jsonl(table, rows, path=jsonl_dir / f"{table}.jsonl")
        tables.append(
            TableExport(
                name=table,
                rows=rows,
                fields=TABLE_FIELDS[table],
                csv_path=csv_path,
                jsonl_path=jsonl_path,
                schema_path=schema_paths[table],
            )
        )

    notebook_path = write_notebook(
        path=notebooks_dir / "reviewer_walkthrough.ipynb"
    )
    write_readme(notebooks_dir / "README.md")
    summary_path = bundle_dir / "reviewer-export-summary.md"
    summary_path.write_text(
        render_reviewer_summary_md(inputs=inputs, tables=tables),
        encoding="utf-8",
    )

    generated_at = generated_at_utc or datetime.now(tz=timezone.utc).isoformat(
        timespec="seconds"
    )
    eid = export_id or f"reviewer-export-{generated_at}"
    export = ReviewerExport(
        export_id=eid,
        generated_at_utc=generated_at,
        bundle_dir=bundle_dir,
        tables=tables,
        notebook_path=notebook_path,
        summary_path=summary_path,
        warnings=list(inputs.warnings),
        source_artifacts=manifest_source_artifacts(inputs),
    )
    write_manifest(export, inputs=inputs, path=bundle_dir / "manifest.json")
    return export


def render_reviewer_summary_md(
    *,
    inputs: LoadedReviewerInputs,
    tables: list[TableExport],
) -> str:
    lines: list[str] = []
    lines.append("# Reviewer Export Summary")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/generate_reviewer_export.py`. "
        "The platform is **not safety-certified**; this export is "
        "engineering review material._"
    )
    lines.append("")
    lines.append("## What this export contains")
    lines.append("")
    lines.append(
        "- Programme health (per-discipline rollups + reasons + triggering artefacts)."
    )
    lines.append(
        "- Trend series across replay quality, analytics scores, qualification counts, gate status."
    )
    lines.append("- Drift findings with severity + description.")
    lines.append("- Subsystem risk (counts + ranking; no causal claims).")
    lines.append("- Gate history (pass / warning / failure / not_executed counts).")
    lines.append("- Replay quality (per-incident score + bag/origin labels).")
    lines.append("- Incident index (severity, outcome, evidence status).")
    lines.append("- Requirement coverage (REQ-* ids + mapped tests/artefacts).")
    lines.append("")

    lines.append("## What this export does NOT contain")
    lines.append("")
    lines.append("- Live runtime evidence not already present in the upstream artefacts.")
    lines.append("- Causal claims about source changes.")
    lines.append("- Predicted future regression.")
    lines.append("- Safety certification of any kind.")
    lines.append("")

    lines.append("## How to read evidence origins")
    lines.append("")
    lines.append("| Origin | Meaning |")
    lines.append("|---|---|")
    lines.append(
        "| `scenario-evidence` | Static scenario fixture (deterministic engine output). |"
    )
    lines.append(
        "| `runtime-evidence` | Static runtime evidence (no live bag). |"
    )
    lines.append(
        "| `live-runtime` | Captured on a Jazzy host (per the runbook). |"
    )
    lines.append(
        "| `bag-backed` | rosbag2 / MCAP artefact present alongside the incident. |"
    )
    lines.append(
        "| `static-source` / `static-workspace` | Source-tree-only signal. |"
    )
    lines.append(
        "| `unknown` | Origin unrecognised — treat conservatively. |"
    )
    lines.append("")

    lines.append("## Static-only and missing-bag evidence")
    lines.append("")
    lines.append(
        "Replay-quality rows record `static_only=true` when the incident "
        "is static-only and `missing_bag=true` when no bag artefact "
        "exists. Both flags are preserved verbatim across the export. "
        "Static-only never silently becomes bag-backed."
    )
    lines.append("")

    lines.append("## How to use the notebook")
    lines.append("")
    lines.append(
        "Open `notebooks/reviewer_walkthrough.ipynb` in Jupyter or VS "
        "Code. No additional dependencies are required; pandas and "
        "matplotlib are imported behind guards. The notebook loads "
        "every CSV from `../csv/` and shows row counts + previews."
    )
    lines.append("")

    lines.append("## Tables emitted")
    lines.append("")
    lines.append("| Table | Rows |")
    lines.append("|---|---|")
    for table in tables:
        lines.append(f"| `{table.name}` | {len(table.rows)} |")
    lines.append("")

    if inputs.warnings:
        lines.append("## Loader warnings")
        lines.append("")
        for w in inputs.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.append("## Known limitations")
    lines.append("")
    for line in DEFAULT_KNOWN_LIMITATIONS:
        lines.append(f"- {line}")
    lines.append("")
    lines.append("## Certification disclaimer")
    lines.append("")
    lines.append(REVIEWER_EXPORT_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)
