"""Programme review report renderers + bundle writer."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from app.programme_review.models import (
    DriftSeverity,
    PROGRAMME_CERTIFICATION_DISCLAIMER,
    ProgrammeReview,
    TrendCategory,
)


def write_programme_review_bundle(
    review: ProgrammeReview, *, out_dir: Path
) -> None:
    """Persist the documented set of programme-review artefacts."""

    out_dir.mkdir(parents=True, exist_ok=True)
    _write_json(out_dir / "index.json", _index_payload(review))
    _write_json(
        out_dir / "programme-health.json", review.governance_health.as_dict()
    )
    _write_json(out_dir / "trend-report.json", review.trend_report.as_dict())
    _write_json(out_dir / "drift-report.json", review.drift_report.as_dict())
    _write_json(
        out_dir / "subsystem-risk-report.json",
        review.subsystem_risk_report.as_dict(),
    )
    _write_json(
        out_dir / "governance-dashboard.json", _dashboard_payload(review)
    )
    _write_json(out_dir / "freshness-report.json", review.freshness_report.as_dict())
    _write_json(
        out_dir / "coverage-evolution.json", review.coverage_evolution.as_dict()
    )
    _write_json(out_dir / "gate-history.json", review.gate_history.as_dict())
    _write_json(out_dir / "programme-review.json", review.as_dict())

    (out_dir / "programme-review.md").write_text(
        render_programme_review_md(review), encoding="utf-8"
    )
    (out_dir / "programme-health.md").write_text(
        render_health_md(review), encoding="utf-8"
    )
    (out_dir / "trend-report.md").write_text(
        render_trend_md(review), encoding="utf-8"
    )
    (out_dir / "drift-report.md").write_text(
        render_drift_md(review), encoding="utf-8"
    )
    (out_dir / "subsystem-risk-report.md").write_text(
        render_subsystem_risk_md(review), encoding="utf-8"
    )
    (out_dir / "freshness-report.md").write_text(
        render_freshness_md(review), encoding="utf-8"
    )
    (out_dir / "coverage-evolution.md").write_text(
        render_coverage_evolution_md(review), encoding="utf-8"
    )
    (out_dir / "gate-history.md").write_text(
        render_gate_history_md(review), encoding="utf-8"
    )


# ---------------------------------------------------------------------------
# Index + dashboard payloads.
# ---------------------------------------------------------------------------


def _index_payload(review: ProgrammeReview) -> dict:
    return {
        "generated_at_utc": review.generated_at_utc,
        "fixture_mode": review.fixture_mode,
        "history_counts": dict(review.history_counts),
        "overall_health": review.governance_health.overall.value,
        "drift_severity": review.drift_report.severity.value,
        "gate_volatility": review.gate_history.volatility.value,
        "freshness_status_counts": review.freshness_report.status_counts(),
        "warnings": list(review.warnings),
    }


def _dashboard_payload(review: ProgrammeReview) -> dict:
    return {
        "generated_at_utc": review.generated_at_utc,
        "overall_health": review.governance_health.overall.value,
        "disciplines": [
            d.as_dict() for d in review.governance_health.disciplines
        ],
        "drift_severity": review.drift_report.severity.value,
        "trend_summary": [
            {
                "label": s.label,
                "category": s.category.value,
                "rolling_3": s.rolling_3.value,
                "rolling_5": s.rolling_5.value,
                "window_size": s.window_size,
            }
            for s in review.trend_report.series
        ],
        "gate_volatility": review.gate_history.volatility.value,
        "gate_sequence": list(review.gate_history.sequence),
        "coverage_evolution_origin_mix": review.coverage_evolution.origin_mix_label,
        "history_counts": dict(review.history_counts),
    }


# ---------------------------------------------------------------------------
# Markdown renderers.
# ---------------------------------------------------------------------------


def render_programme_review_md(review: ProgrammeReview) -> str:
    lines: list[str] = []
    lines.append("# Programme Review")
    lines.append("")
    lines.append(
        "_Generated by `rover_ws/tools/generate_programme_review.py`. "
        "The platform is **not safety-certified**; this report is "
        "engineering governance material._"
    )
    lines.append("")
    lines.append(f"- **Generated:** {review.generated_at_utc}")
    if review.fixture_mode:
        lines.append(
            "- **Fixture mode:** yes — synthetic history fixture, not real history."
        )
    lines.append(
        f"- **Overall health:** `{review.governance_health.overall.value}`"
    )
    lines.append(
        f"- **Drift severity:** `{review.drift_report.severity.value}`"
    )
    lines.append(
        f"- **Gate volatility:** `{review.gate_history.volatility.value}`"
    )
    lines.append("")
    lines.append("## History inventory")
    lines.append("")
    lines.append("| Record type | Count |")
    lines.append("|---|---|")
    for key, value in review.history_counts.items():
        lines.append(f"| `{key}` | {value} |")
    lines.append("")
    if review.warnings:
        lines.append("## Loader warnings")
        lines.append("")
        for w in review.warnings:
            lines.append(f"- {w}")
        lines.append("")
    lines.append("## Governance health")
    lines.append("")
    lines.append("| Discipline | Rating | Reasons |")
    lines.append("|---|---|---|")
    for d in review.governance_health.disciplines:
        reasons = "; ".join(d.reasons) or "-"
        lines.append(
            f"| `{d.category.value}` | `{d.rating.value}` | {reasons} |"
        )
    lines.append("")
    lines.append("## Trends")
    lines.append("")
    lines.append(
        "| Series | Category | Rolling-3 | Rolling-5 | Samples |"
    )
    lines.append("|---|---|---|---|---|")
    for s in review.trend_report.series:
        lines.append(
            f"| `{s.label}` | `{s.category.value}` | "
            f"`{s.rolling_3.value}` | `{s.rolling_5.value}` | {s.window_size} |"
        )
    lines.append("")
    if review.drift_report.findings:
        lines.append("## Drift findings")
        lines.append("")
        lines.append("| Label | Severity | Detail |")
        lines.append("|---|---|---|")
        for f in review.drift_report.findings:
            lines.append(
                f"| `{f.label}` | `{f.severity.value}` | {f.detail} |"
            )
        lines.append("")
    lines.append("## Subsystem risk")
    lines.append("")
    if not review.subsystem_risk_report.rows:
        lines.append("_No subsystem impacts loaded._")
    else:
        lines.append(
            "| Subsystem | Frequency | Repeat regressions | Gate failures | Warnings |"
        )
        lines.append("|---|---|---|---|---|")
        for r in review.subsystem_risk_report.rows:
            lines.append(
                f"| `{r.subsystem}` | {r.frequency} | "
                f"{r.repeat_regression_count} | "
                f"{r.gate_failure_count} | {r.unresolved_warning_count} |"
            )
    lines.append("")
    lines.append("## Coverage evolution")
    lines.append("")
    lines.append(
        f"- **Origin mix:** `{review.coverage_evolution.origin_mix_label}`"
    )
    lines.append(
        f"- **Bag-status distribution:** "
        f"{review.coverage_evolution.bag_status_distribution()}"
    )
    lines.append("")
    lines.append("## Gate history")
    lines.append("")
    lines.append(
        f"- **Last status:** `{review.gate_history.last_status}`"
    )
    lines.append(
        f"- **Last transition:** "
        f"`{review.gate_history.last_transition or 'none'}`"
    )
    lines.append(
        f"- **Counts:** passed={review.gate_history.pass_count} "
        f"warning={review.gate_history.warning_count} "
        f"failed={review.gate_history.failure_count} "
        f"not_executed={review.gate_history.not_executed_count}"
    )
    lines.append("")
    lines.append("## Freshness")
    lines.append("")
    counts = review.freshness_report.status_counts()
    lines.append(
        f"- **Reference time:** `{review.freshness_report.reference_time_utc}`"
    )
    lines.append(
        f"- **Counts:** fresh={counts['fresh']} stale={counts['stale']} "
        f"unknown={counts['unknown']}"
    )
    lines.append("")
    lines.append("## Known limitations")
    lines.append("")
    for line in review.known_limitations:
        lines.append(f"- {line}")
    lines.append("")
    lines.append("## Certification disclaimer")
    lines.append("")
    lines.append(PROGRAMME_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_health_md(review: ProgrammeReview) -> str:
    lines: list[str] = []
    lines.append(f"# Governance Health — `{review.governance_health.overall.value}`")
    lines.append("")
    for d in review.governance_health.disciplines:
        lines.append(f"## `{d.category.value}` — `{d.rating.value}`")
        lines.append("")
        for reason in d.reasons:
            lines.append(f"- {reason}")
        if d.triggering_artifacts:
            lines.append("")
            lines.append("**Triggering artefacts:**")
            for a in d.triggering_artifacts:
                lines.append(f"- `{a}`")
        lines.append("")
    lines.append(PROGRAMME_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_trend_md(review: ProgrammeReview) -> str:
    lines: list[str] = []
    lines.append("# Reliability Trend Report")
    lines.append("")
    lines.append(
        "_Deterministic projections of recorded history. "
        "Insufficient history is reported as such; trends are never "
        "forecast._"
    )
    lines.append("")
    for s in review.trend_report.series:
        lines.append(f"## `{s.label}` — `{s.category.value}`")
        lines.append("")
        lines.append(f"_Detail:_ {s.detail}")
        lines.append("")
        if s.observations:
            lines.append("| Timestamp | Value | Record | Origin |")
            lines.append("|---|---|---|---|")
            for o in s.observations:
                lines.append(
                    f"| `{o.timestamp or '-'}` | "
                    f"{'-' if o.value is None else o.value} | "
                    f"`{o.record_id or '-'}` | `{o.evidence_origin or '-'}` |"
                )
            lines.append("")
    lines.append(PROGRAMME_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_drift_md(review: ProgrammeReview) -> str:
    lines: list[str] = []
    lines.append(f"# Reliability Drift Report — `{review.drift_report.severity.value}`")
    lines.append("")
    counts = review.drift_report.summary_counts()
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for severity, count in counts.items():
        lines.append(f"| `{severity}` | {count} |")
    lines.append("")
    if review.drift_report.findings:
        lines.append("| Label | Severity | Detail |")
        lines.append("|---|---|---|")
        for f in review.drift_report.findings:
            lines.append(
                f"| `{f.label}` | `{f.severity.value}` | {f.detail} |"
            )
        lines.append("")
    else:
        lines.append("_No drift findings._")
        lines.append("")
    lines.append(PROGRAMME_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_subsystem_risk_md(review: ProgrammeReview) -> str:
    lines: list[str] = []
    lines.append("# Subsystem Risk Aggregation")
    lines.append("")
    if not review.subsystem_risk_report.rows:
        lines.append("_No reliability-impact bundles loaded._")
    else:
        lines.append(
            "| Subsystem | Frequency | Repeat regressions | "
            "Gate failures | Warnings | Severity distribution |"
        )
        lines.append("|---|---|---|---|---|---|")
        for r in review.subsystem_risk_report.rows:
            dist = ", ".join(
                f"{k}={v}" for k, v in sorted(r.severity_distribution.items())
            )
            lines.append(
                f"| `{r.subsystem}` | {r.frequency} | "
                f"{r.repeat_regression_count} | {r.gate_failure_count} | "
                f"{r.unresolved_warning_count} | {dist or '-'} |"
            )
        lines.append("")
    lines.append(PROGRAMME_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_freshness_md(review: ProgrammeReview) -> str:
    lines: list[str] = []
    lines.append("# Evidence Freshness Report")
    lines.append("")
    lines.append(
        f"- **Reference time:** `{review.freshness_report.reference_time_utc}`"
    )
    counts = review.freshness_report.status_counts()
    lines.append(f"- **Counts:** {counts}")
    lines.append("")
    lines.append(
        "| Record | Type | Generated | Age (s) | Threshold (s) | Status |"
    )
    lines.append("|---|---|---|---|---|---|")
    for e in review.freshness_report.entries:
        age = "-" if e.age_seconds is None else str(e.age_seconds)
        lines.append(
            f"| `{e.record_id or '-'}` | `{e.record_type}` | "
            f"`{e.generated_at_utc or '-'}` | {age} | "
            f"{e.threshold_seconds} | `{e.status.value}` |"
        )
    lines.append("")
    lines.append(PROGRAMME_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_coverage_evolution_md(review: ProgrammeReview) -> str:
    lines: list[str] = []
    lines.append("# Coverage Evolution")
    lines.append("")
    lines.append(
        f"- **Origin mix:** `{review.coverage_evolution.origin_mix_label}`"
    )
    lines.append("")
    if not review.coverage_evolution.entries:
        lines.append("_No replay-review reports loaded._")
    else:
        lines.append(
            "| Timestamp | Record | Origin | Bag | Coverage | Review | Score |"
        )
        lines.append("|---|---|---|---|---|---|---|")
        for e in review.coverage_evolution.entries:
            lines.append(
                f"| `{e.timestamp or '-'}` | `{e.record_id or '-'}` | "
                f"`{e.evidence_origin}` | `{e.bag_status}` | "
                f"`{e.coverage_status}` | `{e.review_completion_status}` | "
                f"{'-' if e.score is None else e.score} |"
            )
        lines.append("")
    lines.append(PROGRAMME_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def render_gate_history_md(review: ProgrammeReview) -> str:
    lines: list[str] = []
    lines.append("# Gate History")
    lines.append("")
    lines.append(f"- **Last status:** `{review.gate_history.last_status}`")
    lines.append(
        f"- **Volatility:** `{review.gate_history.volatility.value}`"
    )
    lines.append(
        f"- **Last transition:** "
        f"`{review.gate_history.last_transition or 'none'}`"
    )
    lines.append(
        f"- **Counts:** passed={review.gate_history.pass_count} "
        f"warning={review.gate_history.warning_count} "
        f"failed={review.gate_history.failure_count} "
        f"not_executed={review.gate_history.not_executed_count}"
    )
    lines.append("")
    lines.append(
        "**Sequence:** "
        + (
            " -> ".join(f"`{s}`" for s in review.gate_history.sequence)
            or "_no data_"
        )
    )
    lines.append("")
    lines.append(PROGRAMME_CERTIFICATION_DISCLAIMER)
    lines.append("")
    return "\n".join(lines)


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8"
    )
